In [1]:
import turtle
turtle.circle(100,-180)
turtle.circle(200,200)

In [13]:
import torch
x=torch.rand(5,3)
print(x)

tensor([[0.5609, 0.6421, 0.4960],
        [0.0685, 0.3763, 0.2172],
        [0.0402, 0.0708, 0.7035],
        [0.5997, 0.9702, 0.3810],
        [0.5508, 0.3867, 0.1218]])


In [ ]:
import torch
y=torch.arange(12)
print(y)
print(y.reshape(3,-1))
torch.exp(y.reshape(3,-1))
b=y.reshape(3,-1).sum()
print(b)
print(id(b))
b=b+b
print(id(b))

In [ ]:
import torch
x=torch.arange(12).reshape(1,3,-1)
print(x)
y=torch.tensor([[1,2,3,4],[3,4,5,6],[5,6,7,5]])
x>y
print(y)
print(x>y)

In [68]:
# import torch
# a = torch.arange(12).reshape((2,3,2))
# print(a)
# print('\n')
# b = torch.arange(2).reshape((1,1,2))
# print(b)
# print('\n')
# print(a+b)
# a = torch.arange(3).reshape(3, 1)
# print(a)
# b = torch.arange(3).reshape((3, 1))
# print(b)

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]])


tensor([[[0, 1]]])


tensor([[[ 0,  2],
         [ 2,  4],
         [ 4,  6]],

        [[ 6,  8],
         [ 8, 10],
         [10, 12]]])
tensor([[0],
        [1],
        [2]])
tensor([[0],
        [1],
        [2]])


In [2]:
import os
os.makedirs(os.path.join('..', 'data'), exist_ok=True)#创建文件夹
data_file = os.path.join('..', 'data', 'house_tiny.csv')#创建文件
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n') # 列名
    f.write('NA,Pave,127500\n') # 每⾏表⽰⼀个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')
import pandas as pd
data = pd.read_csv(data_file)
print(data)
inputs=data.iloc[:,0:1]
print(inputs)
print('\n')
inputs=inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000
   NumRooms
0       NaN
1       2.0
2       4.0
3       NaN


   NumRooms
0       3.0
1       2.0
2       4.0
3       3.0


In [87]:
a=[123,1233,4,4,5,7,676]
x=a[::-1]#翻转
print(x[1])
a[:-1]#除去最后一个
b=[[123,1233,4,4,5,7,676],[12,3,4,6,7,7,5]]
print(b)
b[1][1]

7
[[123, 1233, 4, 4, 5, 7, 676], [12, 3, 4, 6, 7, 7, 5]]


3

In [33]:
import torch
a=torch.arange(12)
print(a.shape)
a=a.reshape(3,4)
print(a)
a[1]
a[1]=5
print(a)
print(a.shape)#a.shape得到张量的形状，其中总个数为3*4=12个
print(a.numel())#a.numel()得到元素的个数
b=torch.tensor([[[[1,2,3,4,5],[1,3,4,5,6]]],[[[1,2,3,4,5],[1,3,4,5,6]]]])#为张量赋值
b.shape

torch.Size([12])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3],
        [ 5,  5,  5,  5],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])
12


torch.Size([2, 1, 2, 5])

In [63]:
import torch
a=torch.tensor([[6,6,6,6],[6,6,6,6],[6,6,6,6]])
a=a.reshape(3,4)
print(a)
b=torch.tensor([4,5,6,9])
a+b,a*b,a-b,a/b
c=torch.arange(12,dtype=torch.float32).reshape(3,4)
print(c)
x=torch.cat((a,c),dim=0)#按行堆叠
y=torch.cat((a,c),dim=1)#按列堆叠
print(x)
print(y)
x=x.reshape(4,6)
y=y.reshape(4,6)
print(x)
print(y)
print(x>y)

tensor([[6, 6, 6, 6],
        [6, 6, 6, 6],
        [6, 6, 6, 6]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 6.,  6.,  6.,  6.],
        [ 6.,  6.,  6.,  6.],
        [ 6.,  6.,  6.,  6.],
        [ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 6.,  6.,  6.,  6.,  0.,  1.,  2.,  3.],
        [ 6.,  6.,  6.,  6.,  4.,  5.,  6.,  7.],
        [ 6.,  6.,  6.,  6.,  8.,  9., 10., 11.]])
tensor([[ 6.,  6.,  6.,  6.,  6.,  6.],
        [ 6.,  6.,  6.,  6.,  6.,  6.],
        [ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])
tensor([[ 6.,  6.,  6.,  6.,  0.,  1.],
        [ 2.,  3.,  6.,  6.,  6.,  6.],
        [ 4.,  5.,  6.,  7.,  6.,  6.],
        [ 6.,  6.,  8.,  9., 10., 11.]])
tensor([[False, False, False, False,  True,  True],
        [ True,  True, False, False, False, False],
        [False, False, False, False, False, False],
        [False,  True, False, Fa

In [76]:
import torch
a=torch.arange(7).reshape(7,1)
b=torch.arange(3).reshape(1,3)
print(a)
print(b)
a+b#广播机制交叉有1才行
a=a.numpy()
print(a)
a=torch.tensor(a)
print(a)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6]])
tensor([[0, 1, 2]])
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]]
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6]])


In [93]:
import torch 
a=torch.arange(12).reshape(3,4)
print(a)
a[:,1]

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


tensor([1, 5, 9])

In [115]:
import os
os.makedirs(os.path.join('..', 'data'), exist_ok=True)#创建文件夹
data_file = os.path.join('..', 'data', 'house_tiny.csv')#创建文件
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n') # 列名
    f.write('NA,Pave,127500\n') # 每⾏表⽰⼀个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')
import pandas as pd
data = pd.read_csv(data_file)
print(data)
print('\n')
inputs=data.iloc[:,0:2]
print('\n')
print(inputs)
print('\n')
inputs=inputs.fillna(inputs.mean())
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000




   NumRooms Alley
0       NaN  Pave
1       2.0   NaN
2       4.0   NaN
3       NaN   NaN


   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


C:\Windows\Temp\ipykernel_7172\4162172318.py:18: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  inputs=inputs.fillna(inputs.mean())


F1分数的计算公式是精确度（Precision）和召回率（Recall）的调和平均。具体公式如下：

[ F1 = 2 \times \frac{\text{Precision} \times \text{Recall}}{\text{Precision} + \text{Recall}} ]

其中：

精确度（Precision） 是指模型正确预测为正类的样本数与模型预测为正类的总样本数之比。计算公式为：[ \text{Precision} = \frac{\text{True Positives (TP)}}{\text{True Positives (TP)} + \text{False Positives (FP)}} ]
召回率（Recall） 是指模型正确预测为正类的样本数与实际正类的总样本数之比。计算公式为：[ \text{Recall} = \frac{\text{True Positives (TP)}}{\text{True Positives (TP)} + \text{False Negatives (FN)}} ]
在这些定义中：

True Positives (TP) 是正确预测的正类样本数。
False Positives (FP) 是错误预测为正类的负类样本数。
False Negatives (FN) 是错误预测为负类的正类样本数。
F1分数是一个衡量模型准确性的综合指标，尤其在类别不平衡的情况下比单纯的准确度更为有效。它在精确度和召回率之间找到了一个平衡点，尤其适用于那些对假阳性和假阴性同等重视的场景