In [4]:
import torch

# 随机生成一个预测结果的张量（对应4个样本，3个类别）
x1 = torch.tensor([[10.0, -10.0, -10.0],
                   [-10.0, 10.0, -10.0],
                   [-10.0, -10.0, 10.0],
                   [10.0, -10.0, -10.0]])

# 真实的类别标签
y1 = torch.tensor([0, 1, 2, 0])

# 使用交叉熵损失函数计算损失
loss = torch.nn.CrossEntropyLoss()
l = loss(x1, y1)

print(l.item())

tensor(0.5514)


AttributeError: 'numpy.ndarray' object has no attribute 'GetWidth'

In [3]:
import torch

# 创建一个示例二维张量
x = torch.tensor([[1.0, 2.0, 3.0],
                  [4.0, 5.0, 6.0]])


mean_along_dim0 = torch.mean(x)
print(mean_along_dim0)


tensor(3.5000)


In [9]:
import torch
a=torch.randint(0,2,(1,3,2,2,2))
print(a)
b=(a==0).float()
print(b)


tensor([[[[[1, 0],
           [1, 0]],

          [[0, 1],
           [1, 0]]],


         [[[1, 0],
           [0, 1]],

          [[0, 1],
           [0, 1]]],


         [[[0, 1],
           [1, 1]],

          [[0, 1],
           [0, 0]]]]])
tensor([[[[[0., 1.],
           [0., 1.]],

          [[1., 0.],
           [0., 1.]]],


         [[[0., 1.],
           [1., 0.]],

          [[1., 0.],
           [1., 0.]]],


         [[[1., 0.],
           [0., 0.]],

          [[1., 0.],
           [1., 1.]]]]])


In [8]:
c=b*a
print(c)

tensor([[[[[0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.]]],


         [[[0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.]]],


         [[[0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.]]]]])


In [13]:
a=torch.randint(1,3,(1,2,3,4))
print(a)
b=torch.sum(a,dim=(1,2,3))
b

tensor([[[[1, 2, 1, 2],
          [1, 1, 1, 2],
          [2, 1, 1, 1]],

         [[2, 2, 1, 2],
          [1, 1, 2, 2],
          [2, 2, 2, 2]]]])


tensor([37])

In [17]:
import numpy as np
img=[np.ndarray([[1,2,3],[1,3,4]]),np.ndarray([[1,3,3],[13,34,123]])]
im = img if isinstance(img, np.ndarray) else img[0]
print(im)

TypeError: 'list' object cannot be interpreted as an integer